name: Build Executables

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Linux系统需要安装7z
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get install p7zip-full -y

    # macOS系统需要安装7z
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install p7zip

    - name: Build executable with PyInstaller
      run: |
        pyinstaller build.spec --noconfirm --clean
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compress_tool-${{ runner.os }}
        path: |
          dist/
          build/
        if-no-files-found: error 